# Generated by Django 2.0 on 2018-04-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20180429_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_html',
            field=models.TextField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
