# Generated by Django 2.0 on 2018-04-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(db_column='bio', default=1, max_length=100),
            preserve_default=False,
        ),
    ]
