# Generated by Django 2.0 on 2018-05-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_post_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
