# Generated by Django 2.0 on 2018-05-09 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0019_auto_20180509_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='users',
        ),
        migrations.AddField(
            model_name='post',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
